// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/good-manager/pkg/db/ent/appgood"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// AppGoodCreate is the builder for creating a AppGood entity.
type AppGoodCreate struct {
	config
	mutation *AppGoodMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (agc *AppGoodCreate) SetCreatedAt(u uint32) *AppGoodCreate {
	agc.mutation.SetCreatedAt(u)
	return agc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableCreatedAt(u *uint32) *AppGoodCreate {
	if u != nil {
		agc.SetCreatedAt(*u)
	}
	return agc
}

// SetUpdatedAt sets the "updated_at" field.
func (agc *AppGoodCreate) SetUpdatedAt(u uint32) *AppGoodCreate {
	agc.mutation.SetUpdatedAt(u)
	return agc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableUpdatedAt(u *uint32) *AppGoodCreate {
	if u != nil {
		agc.SetUpdatedAt(*u)
	}
	return agc
}

// SetDeletedAt sets the "deleted_at" field.
func (agc *AppGoodCreate) SetDeletedAt(u uint32) *AppGoodCreate {
	agc.mutation.SetDeletedAt(u)
	return agc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableDeletedAt(u *uint32) *AppGoodCreate {
	if u != nil {
		agc.SetDeletedAt(*u)
	}
	return agc
}

// SetAppID sets the "app_id" field.
func (agc *AppGoodCreate) SetAppID(u uuid.UUID) *AppGoodCreate {
	agc.mutation.SetAppID(u)
	return agc
}

// SetGoodID sets the "good_id" field.
func (agc *AppGoodCreate) SetGoodID(u uuid.UUID) *AppGoodCreate {
	agc.mutation.SetGoodID(u)
	return agc
}

// SetOnline sets the "online" field.
func (agc *AppGoodCreate) SetOnline(b bool) *AppGoodCreate {
	agc.mutation.SetOnline(b)
	return agc
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableOnline(b *bool) *AppGoodCreate {
	if b != nil {
		agc.SetOnline(*b)
	}
	return agc
}

// SetVisible sets the "visible" field.
func (agc *AppGoodCreate) SetVisible(b bool) *AppGoodCreate {
	agc.mutation.SetVisible(b)
	return agc
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableVisible(b *bool) *AppGoodCreate {
	if b != nil {
		agc.SetVisible(*b)
	}
	return agc
}

// SetGoodName sets the "good_name" field.
func (agc *AppGoodCreate) SetGoodName(s string) *AppGoodCreate {
	agc.mutation.SetGoodName(s)
	return agc
}

// SetNillableGoodName sets the "good_name" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableGoodName(s *string) *AppGoodCreate {
	if s != nil {
		agc.SetGoodName(*s)
	}
	return agc
}

// SetPrice sets the "price" field.
func (agc *AppGoodCreate) SetPrice(d decimal.Decimal) *AppGoodCreate {
	agc.mutation.SetPrice(d)
	return agc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillablePrice(d *decimal.Decimal) *AppGoodCreate {
	if d != nil {
		agc.SetPrice(*d)
	}
	return agc
}

// SetDisplayIndex sets the "display_index" field.
func (agc *AppGoodCreate) SetDisplayIndex(i int32) *AppGoodCreate {
	agc.mutation.SetDisplayIndex(i)
	return agc
}

// SetNillableDisplayIndex sets the "display_index" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableDisplayIndex(i *int32) *AppGoodCreate {
	if i != nil {
		agc.SetDisplayIndex(*i)
	}
	return agc
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (agc *AppGoodCreate) SetPurchaseLimit(i int32) *AppGoodCreate {
	agc.mutation.SetPurchaseLimit(i)
	return agc
}

// SetNillablePurchaseLimit sets the "purchase_limit" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillablePurchaseLimit(i *int32) *AppGoodCreate {
	if i != nil {
		agc.SetPurchaseLimit(*i)
	}
	return agc
}

// SetCommissionPercent sets the "commission_percent" field.
func (agc *AppGoodCreate) SetCommissionPercent(i int32) *AppGoodCreate {
	agc.mutation.SetCommissionPercent(i)
	return agc
}

// SetNillableCommissionPercent sets the "commission_percent" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableCommissionPercent(i *int32) *AppGoodCreate {
	if i != nil {
		agc.SetCommissionPercent(*i)
	}
	return agc
}

// SetID sets the "id" field.
func (agc *AppGoodCreate) SetID(u uuid.UUID) *AppGoodCreate {
	agc.mutation.SetID(u)
	return agc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (agc *AppGoodCreate) SetNillableID(u *uuid.UUID) *AppGoodCreate {
	if u != nil {
		agc.SetID(*u)
	}
	return agc
}

// Mutation returns the AppGoodMutation object of the builder.
func (agc *AppGoodCreate) Mutation() *AppGoodMutation {
	return agc.mutation
}

// Save creates the AppGood in the database.
func (agc *AppGoodCreate) Save(ctx context.Context) (*AppGood, error) {
	var (
		err  error
		node *AppGood
	)
	if err := agc.defaults(); err != nil {
		return nil, err
	}
	if len(agc.hooks) == 0 {
		if err = agc.check(); err != nil {
			return nil, err
		}
		node, err = agc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppGoodMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = agc.check(); err != nil {
				return nil, err
			}
			agc.mutation = mutation
			if node, err = agc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(agc.hooks) - 1; i >= 0; i-- {
			if agc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = agc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, agc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AppGood)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AppGoodMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (agc *AppGoodCreate) SaveX(ctx context.Context) *AppGood {
	v, err := agc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agc *AppGoodCreate) Exec(ctx context.Context) error {
	_, err := agc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agc *AppGoodCreate) ExecX(ctx context.Context) {
	if err := agc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (agc *AppGoodCreate) defaults() error {
	if _, ok := agc.mutation.CreatedAt(); !ok {
		if appgood.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized appgood.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := appgood.DefaultCreatedAt()
		agc.mutation.SetCreatedAt(v)
	}
	if _, ok := agc.mutation.UpdatedAt(); !ok {
		if appgood.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized appgood.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := appgood.DefaultUpdatedAt()
		agc.mutation.SetUpdatedAt(v)
	}
	if _, ok := agc.mutation.DeletedAt(); !ok {
		if appgood.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized appgood.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := appgood.DefaultDeletedAt()
		agc.mutation.SetDeletedAt(v)
	}
	if _, ok := agc.mutation.Online(); !ok {
		v := appgood.DefaultOnline
		agc.mutation.SetOnline(v)
	}
	if _, ok := agc.mutation.Visible(); !ok {
		v := appgood.DefaultVisible
		agc.mutation.SetVisible(v)
	}
	if _, ok := agc.mutation.GoodName(); !ok {
		v := appgood.DefaultGoodName
		agc.mutation.SetGoodName(v)
	}
	if _, ok := agc.mutation.Price(); !ok {
		v := appgood.DefaultPrice
		agc.mutation.SetPrice(v)
	}
	if _, ok := agc.mutation.DisplayIndex(); !ok {
		v := appgood.DefaultDisplayIndex
		agc.mutation.SetDisplayIndex(v)
	}
	if _, ok := agc.mutation.PurchaseLimit(); !ok {
		v := appgood.DefaultPurchaseLimit
		agc.mutation.SetPurchaseLimit(v)
	}
	if _, ok := agc.mutation.CommissionPercent(); !ok {
		v := appgood.DefaultCommissionPercent
		agc.mutation.SetCommissionPercent(v)
	}
	if _, ok := agc.mutation.ID(); !ok {
		if appgood.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized appgood.DefaultID (forgotten import ent/runtime?)")
		}
		v := appgood.DefaultID()
		agc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (agc *AppGoodCreate) check() error {
	if _, ok := agc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppGood.created_at"`)}
	}
	if _, ok := agc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppGood.updated_at"`)}
	}
	if _, ok := agc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "AppGood.deleted_at"`)}
	}
	if _, ok := agc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "AppGood.app_id"`)}
	}
	if _, ok := agc.mutation.GoodID(); !ok {
		return &ValidationError{Name: "good_id", err: errors.New(`ent: missing required field "AppGood.good_id"`)}
	}
	return nil
}

func (agc *AppGoodCreate) sqlSave(ctx context.Context) (*AppGood, error) {
	_node, _spec := agc.createSpec()
	if err := sqlgraph.CreateNode(ctx, agc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (agc *AppGoodCreate) createSpec() (*AppGood, *sqlgraph.CreateSpec) {
	var (
		_node = &AppGood{config: agc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: appgood.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appgood.FieldID,
			},
		}
	)
	_spec.OnConflict = agc.conflict
	if id, ok := agc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := agc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appgood.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := agc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appgood.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := agc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: appgood.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := agc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appgood.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := agc.mutation.GoodID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: appgood.FieldGoodID,
		})
		_node.GoodID = value
	}
	if value, ok := agc.mutation.Online(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: appgood.FieldOnline,
		})
		_node.Online = value
	}
	if value, ok := agc.mutation.Visible(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: appgood.FieldVisible,
		})
		_node.Visible = value
	}
	if value, ok := agc.mutation.GoodName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: appgood.FieldGoodName,
		})
		_node.GoodName = value
	}
	if value, ok := agc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: appgood.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := agc.mutation.DisplayIndex(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: appgood.FieldDisplayIndex,
		})
		_node.DisplayIndex = value
	}
	if value, ok := agc.mutation.PurchaseLimit(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: appgood.FieldPurchaseLimit,
		})
		_node.PurchaseLimit = value
	}
	if value, ok := agc.mutation.CommissionPercent(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: appgood.FieldCommissionPercent,
		})
		_node.CommissionPercent = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppGood.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppGoodUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (agc *AppGoodCreate) OnConflict(opts ...sql.ConflictOption) *AppGoodUpsertOne {
	agc.conflict = opts
	return &AppGoodUpsertOne{
		create: agc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppGood.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (agc *AppGoodCreate) OnConflictColumns(columns ...string) *AppGoodUpsertOne {
	agc.conflict = append(agc.conflict, sql.ConflictColumns(columns...))
	return &AppGoodUpsertOne{
		create: agc,
	}
}

type (
	// AppGoodUpsertOne is the builder for "upsert"-ing
	//  one AppGood node.
	AppGoodUpsertOne struct {
		create *AppGoodCreate
	}

	// AppGoodUpsert is the "OnConflict" setter.
	AppGoodUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *AppGoodUpsert) SetCreatedAt(v uint32) *AppGoodUpsert {
	u.Set(appgood.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateCreatedAt() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *AppGoodUpsert) AddCreatedAt(v uint32) *AppGoodUpsert {
	u.Add(appgood.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppGoodUpsert) SetUpdatedAt(v uint32) *AppGoodUpsert {
	u.Set(appgood.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateUpdatedAt() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *AppGoodUpsert) AddUpdatedAt(v uint32) *AppGoodUpsert {
	u.Add(appgood.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AppGoodUpsert) SetDeletedAt(v uint32) *AppGoodUpsert {
	u.Set(appgood.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateDeletedAt() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AppGoodUpsert) AddDeletedAt(v uint32) *AppGoodUpsert {
	u.Add(appgood.FieldDeletedAt, v)
	return u
}

// SetAppID sets the "app_id" field.
func (u *AppGoodUpsert) SetAppID(v uuid.UUID) *AppGoodUpsert {
	u.Set(appgood.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateAppID() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldAppID)
	return u
}

// SetGoodID sets the "good_id" field.
func (u *AppGoodUpsert) SetGoodID(v uuid.UUID) *AppGoodUpsert {
	u.Set(appgood.FieldGoodID, v)
	return u
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateGoodID() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldGoodID)
	return u
}

// SetOnline sets the "online" field.
func (u *AppGoodUpsert) SetOnline(v bool) *AppGoodUpsert {
	u.Set(appgood.FieldOnline, v)
	return u
}

// UpdateOnline sets the "online" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateOnline() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldOnline)
	return u
}

// ClearOnline clears the value of the "online" field.
func (u *AppGoodUpsert) ClearOnline() *AppGoodUpsert {
	u.SetNull(appgood.FieldOnline)
	return u
}

// SetVisible sets the "visible" field.
func (u *AppGoodUpsert) SetVisible(v bool) *AppGoodUpsert {
	u.Set(appgood.FieldVisible, v)
	return u
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateVisible() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldVisible)
	return u
}

// ClearVisible clears the value of the "visible" field.
func (u *AppGoodUpsert) ClearVisible() *AppGoodUpsert {
	u.SetNull(appgood.FieldVisible)
	return u
}

// SetGoodName sets the "good_name" field.
func (u *AppGoodUpsert) SetGoodName(v string) *AppGoodUpsert {
	u.Set(appgood.FieldGoodName, v)
	return u
}

// UpdateGoodName sets the "good_name" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateGoodName() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldGoodName)
	return u
}

// ClearGoodName clears the value of the "good_name" field.
func (u *AppGoodUpsert) ClearGoodName() *AppGoodUpsert {
	u.SetNull(appgood.FieldGoodName)
	return u
}

// SetPrice sets the "price" field.
func (u *AppGoodUpsert) SetPrice(v decimal.Decimal) *AppGoodUpsert {
	u.Set(appgood.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdatePrice() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldPrice)
	return u
}

// ClearPrice clears the value of the "price" field.
func (u *AppGoodUpsert) ClearPrice() *AppGoodUpsert {
	u.SetNull(appgood.FieldPrice)
	return u
}

// SetDisplayIndex sets the "display_index" field.
func (u *AppGoodUpsert) SetDisplayIndex(v int32) *AppGoodUpsert {
	u.Set(appgood.FieldDisplayIndex, v)
	return u
}

// UpdateDisplayIndex sets the "display_index" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateDisplayIndex() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldDisplayIndex)
	return u
}

// AddDisplayIndex adds v to the "display_index" field.
func (u *AppGoodUpsert) AddDisplayIndex(v int32) *AppGoodUpsert {
	u.Add(appgood.FieldDisplayIndex, v)
	return u
}

// ClearDisplayIndex clears the value of the "display_index" field.
func (u *AppGoodUpsert) ClearDisplayIndex() *AppGoodUpsert {
	u.SetNull(appgood.FieldDisplayIndex)
	return u
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (u *AppGoodUpsert) SetPurchaseLimit(v int32) *AppGoodUpsert {
	u.Set(appgood.FieldPurchaseLimit, v)
	return u
}

// UpdatePurchaseLimit sets the "purchase_limit" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdatePurchaseLimit() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldPurchaseLimit)
	return u
}

// AddPurchaseLimit adds v to the "purchase_limit" field.
func (u *AppGoodUpsert) AddPurchaseLimit(v int32) *AppGoodUpsert {
	u.Add(appgood.FieldPurchaseLimit, v)
	return u
}

// ClearPurchaseLimit clears the value of the "purchase_limit" field.
func (u *AppGoodUpsert) ClearPurchaseLimit() *AppGoodUpsert {
	u.SetNull(appgood.FieldPurchaseLimit)
	return u
}

// SetCommissionPercent sets the "commission_percent" field.
func (u *AppGoodUpsert) SetCommissionPercent(v int32) *AppGoodUpsert {
	u.Set(appgood.FieldCommissionPercent, v)
	return u
}

// UpdateCommissionPercent sets the "commission_percent" field to the value that was provided on create.
func (u *AppGoodUpsert) UpdateCommissionPercent() *AppGoodUpsert {
	u.SetExcluded(appgood.FieldCommissionPercent)
	return u
}

// AddCommissionPercent adds v to the "commission_percent" field.
func (u *AppGoodUpsert) AddCommissionPercent(v int32) *AppGoodUpsert {
	u.Add(appgood.FieldCommissionPercent, v)
	return u
}

// ClearCommissionPercent clears the value of the "commission_percent" field.
func (u *AppGoodUpsert) ClearCommissionPercent() *AppGoodUpsert {
	u.SetNull(appgood.FieldCommissionPercent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AppGood.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(appgood.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *AppGoodUpsertOne) UpdateNewValues() *AppGoodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(appgood.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.AppGood.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *AppGoodUpsertOne) Ignore() *AppGoodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppGoodUpsertOne) DoNothing() *AppGoodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppGoodCreate.OnConflict
// documentation for more info.
func (u *AppGoodUpsertOne) Update(set func(*AppGoodUpsert)) *AppGoodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppGoodUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AppGoodUpsertOne) SetCreatedAt(v uint32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *AppGoodUpsertOne) AddCreatedAt(v uint32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateCreatedAt() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppGoodUpsertOne) SetUpdatedAt(v uint32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *AppGoodUpsertOne) AddUpdatedAt(v uint32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateUpdatedAt() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AppGoodUpsertOne) SetDeletedAt(v uint32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AppGoodUpsertOne) AddDeletedAt(v uint32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateDeletedAt() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *AppGoodUpsertOne) SetAppID(v uuid.UUID) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateAppID() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateAppID()
	})
}

// SetGoodID sets the "good_id" field.
func (u *AppGoodUpsertOne) SetGoodID(v uuid.UUID) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetGoodID(v)
	})
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateGoodID() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateGoodID()
	})
}

// SetOnline sets the "online" field.
func (u *AppGoodUpsertOne) SetOnline(v bool) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetOnline(v)
	})
}

// UpdateOnline sets the "online" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateOnline() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateOnline()
	})
}

// ClearOnline clears the value of the "online" field.
func (u *AppGoodUpsertOne) ClearOnline() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearOnline()
	})
}

// SetVisible sets the "visible" field.
func (u *AppGoodUpsertOne) SetVisible(v bool) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetVisible(v)
	})
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateVisible() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateVisible()
	})
}

// ClearVisible clears the value of the "visible" field.
func (u *AppGoodUpsertOne) ClearVisible() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearVisible()
	})
}

// SetGoodName sets the "good_name" field.
func (u *AppGoodUpsertOne) SetGoodName(v string) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetGoodName(v)
	})
}

// UpdateGoodName sets the "good_name" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateGoodName() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateGoodName()
	})
}

// ClearGoodName clears the value of the "good_name" field.
func (u *AppGoodUpsertOne) ClearGoodName() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearGoodName()
	})
}

// SetPrice sets the "price" field.
func (u *AppGoodUpsertOne) SetPrice(v decimal.Decimal) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdatePrice() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdatePrice()
	})
}

// ClearPrice clears the value of the "price" field.
func (u *AppGoodUpsertOne) ClearPrice() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearPrice()
	})
}

// SetDisplayIndex sets the "display_index" field.
func (u *AppGoodUpsertOne) SetDisplayIndex(v int32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetDisplayIndex(v)
	})
}

// AddDisplayIndex adds v to the "display_index" field.
func (u *AppGoodUpsertOne) AddDisplayIndex(v int32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddDisplayIndex(v)
	})
}

// UpdateDisplayIndex sets the "display_index" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateDisplayIndex() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateDisplayIndex()
	})
}

// ClearDisplayIndex clears the value of the "display_index" field.
func (u *AppGoodUpsertOne) ClearDisplayIndex() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearDisplayIndex()
	})
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (u *AppGoodUpsertOne) SetPurchaseLimit(v int32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetPurchaseLimit(v)
	})
}

// AddPurchaseLimit adds v to the "purchase_limit" field.
func (u *AppGoodUpsertOne) AddPurchaseLimit(v int32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddPurchaseLimit(v)
	})
}

// UpdatePurchaseLimit sets the "purchase_limit" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdatePurchaseLimit() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdatePurchaseLimit()
	})
}

// ClearPurchaseLimit clears the value of the "purchase_limit" field.
func (u *AppGoodUpsertOne) ClearPurchaseLimit() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearPurchaseLimit()
	})
}

// SetCommissionPercent sets the "commission_percent" field.
func (u *AppGoodUpsertOne) SetCommissionPercent(v int32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetCommissionPercent(v)
	})
}

// AddCommissionPercent adds v to the "commission_percent" field.
func (u *AppGoodUpsertOne) AddCommissionPercent(v int32) *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddCommissionPercent(v)
	})
}

// UpdateCommissionPercent sets the "commission_percent" field to the value that was provided on create.
func (u *AppGoodUpsertOne) UpdateCommissionPercent() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateCommissionPercent()
	})
}

// ClearCommissionPercent clears the value of the "commission_percent" field.
func (u *AppGoodUpsertOne) ClearCommissionPercent() *AppGoodUpsertOne {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearCommissionPercent()
	})
}

// Exec executes the query.
func (u *AppGoodUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppGoodCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppGoodUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppGoodUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AppGoodUpsertOne.ID is not supported by MySQL driver. Use AppGoodUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppGoodUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppGoodCreateBulk is the builder for creating many AppGood entities in bulk.
type AppGoodCreateBulk struct {
	config
	builders []*AppGoodCreate
	conflict []sql.ConflictOption
}

// Save creates the AppGood entities in the database.
func (agcb *AppGoodCreateBulk) Save(ctx context.Context) ([]*AppGood, error) {
	specs := make([]*sqlgraph.CreateSpec, len(agcb.builders))
	nodes := make([]*AppGood, len(agcb.builders))
	mutators := make([]Mutator, len(agcb.builders))
	for i := range agcb.builders {
		func(i int, root context.Context) {
			builder := agcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppGoodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, agcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = agcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, agcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, agcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (agcb *AppGoodCreateBulk) SaveX(ctx context.Context) []*AppGood {
	v, err := agcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agcb *AppGoodCreateBulk) Exec(ctx context.Context) error {
	_, err := agcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agcb *AppGoodCreateBulk) ExecX(ctx context.Context) {
	if err := agcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppGood.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppGoodUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (agcb *AppGoodCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppGoodUpsertBulk {
	agcb.conflict = opts
	return &AppGoodUpsertBulk{
		create: agcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppGood.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (agcb *AppGoodCreateBulk) OnConflictColumns(columns ...string) *AppGoodUpsertBulk {
	agcb.conflict = append(agcb.conflict, sql.ConflictColumns(columns...))
	return &AppGoodUpsertBulk{
		create: agcb,
	}
}

// AppGoodUpsertBulk is the builder for "upsert"-ing
// a bulk of AppGood nodes.
type AppGoodUpsertBulk struct {
	create *AppGoodCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppGood.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(appgood.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *AppGoodUpsertBulk) UpdateNewValues() *AppGoodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(appgood.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppGood.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *AppGoodUpsertBulk) Ignore() *AppGoodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppGoodUpsertBulk) DoNothing() *AppGoodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppGoodCreateBulk.OnConflict
// documentation for more info.
func (u *AppGoodUpsertBulk) Update(set func(*AppGoodUpsert)) *AppGoodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppGoodUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AppGoodUpsertBulk) SetCreatedAt(v uint32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *AppGoodUpsertBulk) AddCreatedAt(v uint32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateCreatedAt() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppGoodUpsertBulk) SetUpdatedAt(v uint32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *AppGoodUpsertBulk) AddUpdatedAt(v uint32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateUpdatedAt() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AppGoodUpsertBulk) SetDeletedAt(v uint32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *AppGoodUpsertBulk) AddDeletedAt(v uint32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateDeletedAt() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *AppGoodUpsertBulk) SetAppID(v uuid.UUID) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateAppID() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateAppID()
	})
}

// SetGoodID sets the "good_id" field.
func (u *AppGoodUpsertBulk) SetGoodID(v uuid.UUID) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetGoodID(v)
	})
}

// UpdateGoodID sets the "good_id" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateGoodID() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateGoodID()
	})
}

// SetOnline sets the "online" field.
func (u *AppGoodUpsertBulk) SetOnline(v bool) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetOnline(v)
	})
}

// UpdateOnline sets the "online" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateOnline() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateOnline()
	})
}

// ClearOnline clears the value of the "online" field.
func (u *AppGoodUpsertBulk) ClearOnline() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearOnline()
	})
}

// SetVisible sets the "visible" field.
func (u *AppGoodUpsertBulk) SetVisible(v bool) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetVisible(v)
	})
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateVisible() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateVisible()
	})
}

// ClearVisible clears the value of the "visible" field.
func (u *AppGoodUpsertBulk) ClearVisible() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearVisible()
	})
}

// SetGoodName sets the "good_name" field.
func (u *AppGoodUpsertBulk) SetGoodName(v string) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetGoodName(v)
	})
}

// UpdateGoodName sets the "good_name" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateGoodName() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateGoodName()
	})
}

// ClearGoodName clears the value of the "good_name" field.
func (u *AppGoodUpsertBulk) ClearGoodName() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearGoodName()
	})
}

// SetPrice sets the "price" field.
func (u *AppGoodUpsertBulk) SetPrice(v decimal.Decimal) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdatePrice() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdatePrice()
	})
}

// ClearPrice clears the value of the "price" field.
func (u *AppGoodUpsertBulk) ClearPrice() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearPrice()
	})
}

// SetDisplayIndex sets the "display_index" field.
func (u *AppGoodUpsertBulk) SetDisplayIndex(v int32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetDisplayIndex(v)
	})
}

// AddDisplayIndex adds v to the "display_index" field.
func (u *AppGoodUpsertBulk) AddDisplayIndex(v int32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddDisplayIndex(v)
	})
}

// UpdateDisplayIndex sets the "display_index" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateDisplayIndex() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateDisplayIndex()
	})
}

// ClearDisplayIndex clears the value of the "display_index" field.
func (u *AppGoodUpsertBulk) ClearDisplayIndex() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearDisplayIndex()
	})
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (u *AppGoodUpsertBulk) SetPurchaseLimit(v int32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetPurchaseLimit(v)
	})
}

// AddPurchaseLimit adds v to the "purchase_limit" field.
func (u *AppGoodUpsertBulk) AddPurchaseLimit(v int32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddPurchaseLimit(v)
	})
}

// UpdatePurchaseLimit sets the "purchase_limit" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdatePurchaseLimit() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdatePurchaseLimit()
	})
}

// ClearPurchaseLimit clears the value of the "purchase_limit" field.
func (u *AppGoodUpsertBulk) ClearPurchaseLimit() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearPurchaseLimit()
	})
}

// SetCommissionPercent sets the "commission_percent" field.
func (u *AppGoodUpsertBulk) SetCommissionPercent(v int32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.SetCommissionPercent(v)
	})
}

// AddCommissionPercent adds v to the "commission_percent" field.
func (u *AppGoodUpsertBulk) AddCommissionPercent(v int32) *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.AddCommissionPercent(v)
	})
}

// UpdateCommissionPercent sets the "commission_percent" field to the value that was provided on create.
func (u *AppGoodUpsertBulk) UpdateCommissionPercent() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.UpdateCommissionPercent()
	})
}

// ClearCommissionPercent clears the value of the "commission_percent" field.
func (u *AppGoodUpsertBulk) ClearCommissionPercent() *AppGoodUpsertBulk {
	return u.Update(func(s *AppGoodUpsert) {
		s.ClearCommissionPercent()
	})
}

// Exec executes the query.
func (u *AppGoodUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppGoodCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppGoodCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppGoodUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
