// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/good-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/good-manager/pkg/db/ent/stockv1"
)

// StockV1Delete is the builder for deleting a StockV1 entity.
type StockV1Delete struct {
	config
	hooks    []Hook
	mutation *StockV1Mutation
}

// Where appends a list predicates to the StockV1Delete builder.
func (sv *StockV1Delete) Where(ps ...predicate.StockV1) *StockV1Delete {
	sv.mutation.Where(ps...)
	return sv
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sv *StockV1Delete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sv.hooks) == 0 {
		affected, err = sv.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StockV1Mutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sv.mutation = mutation
			affected, err = sv.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sv.hooks) - 1; i >= 0; i-- {
			if sv.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sv.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sv.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sv *StockV1Delete) ExecX(ctx context.Context) int {
	n, err := sv.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sv *StockV1Delete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: stockv1.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: stockv1.FieldID,
			},
		},
	}
	if ps := sv.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sv.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// StockV1DeleteOne is the builder for deleting a single StockV1 entity.
type StockV1DeleteOne struct {
	sv *StockV1Delete
}

// Exec executes the deletion query.
func (svo *StockV1DeleteOne) Exec(ctx context.Context) error {
	n, err := svo.sv.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{stockv1.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (svo *StockV1DeleteOne) ExecX(ctx context.Context) {
	svo.sv.ExecX(ctx)
}
