// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/good-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/good-manager/pkg/db/ent/stockv1"
	"github.com/google/uuid"
)

// StockV1Query is the builder for querying StockV1 entities.
type StockV1Query struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StockV1
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockV1Query builder.
func (sv *StockV1Query) Where(ps ...predicate.StockV1) *StockV1Query {
	sv.predicates = append(sv.predicates, ps...)
	return sv
}

// Limit adds a limit step to the query.
func (sv *StockV1Query) Limit(limit int) *StockV1Query {
	sv.limit = &limit
	return sv
}

// Offset adds an offset step to the query.
func (sv *StockV1Query) Offset(offset int) *StockV1Query {
	sv.offset = &offset
	return sv
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sv *StockV1Query) Unique(unique bool) *StockV1Query {
	sv.unique = &unique
	return sv
}

// Order adds an order step to the query.
func (sv *StockV1Query) Order(o ...OrderFunc) *StockV1Query {
	sv.order = append(sv.order, o...)
	return sv
}

// First returns the first StockV1 entity from the query.
// Returns a *NotFoundError when no StockV1 was found.
func (sv *StockV1Query) First(ctx context.Context) (*StockV1, error) {
	nodes, err := sv.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stockv1.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sv *StockV1Query) FirstX(ctx context.Context) *StockV1 {
	node, err := sv.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StockV1 ID from the query.
// Returns a *NotFoundError when no StockV1 ID was found.
func (sv *StockV1Query) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sv.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stockv1.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sv *StockV1Query) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := sv.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StockV1 entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StockV1 entity is found.
// Returns a *NotFoundError when no StockV1 entities are found.
func (sv *StockV1Query) Only(ctx context.Context) (*StockV1, error) {
	nodes, err := sv.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stockv1.Label}
	default:
		return nil, &NotSingularError{stockv1.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sv *StockV1Query) OnlyX(ctx context.Context) *StockV1 {
	node, err := sv.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StockV1 ID in the query.
// Returns a *NotSingularError when more than one StockV1 ID is found.
// Returns a *NotFoundError when no entities are found.
func (sv *StockV1Query) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sv.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stockv1.Label}
	default:
		err = &NotSingularError{stockv1.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sv *StockV1Query) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := sv.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StockV1s.
func (sv *StockV1Query) All(ctx context.Context) ([]*StockV1, error) {
	if err := sv.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sv.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sv *StockV1Query) AllX(ctx context.Context) []*StockV1 {
	nodes, err := sv.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StockV1 IDs.
func (sv *StockV1Query) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := sv.Select(stockv1.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sv *StockV1Query) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := sv.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sv *StockV1Query) Count(ctx context.Context) (int, error) {
	if err := sv.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sv.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sv *StockV1Query) CountX(ctx context.Context) int {
	count, err := sv.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sv *StockV1Query) Exist(ctx context.Context) (bool, error) {
	if err := sv.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sv.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sv *StockV1Query) ExistX(ctx context.Context) bool {
	exist, err := sv.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockV1Query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sv *StockV1Query) Clone() *StockV1Query {
	if sv == nil {
		return nil
	}
	return &StockV1Query{
		config:     sv.config,
		limit:      sv.limit,
		offset:     sv.offset,
		order:      append([]OrderFunc{}, sv.order...),
		predicates: append([]predicate.StockV1{}, sv.predicates...),
		// clone intermediate query.
		sql:    sv.sql.Clone(),
		path:   sv.path,
		unique: sv.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StockV1.Query().
//		GroupBy(stockv1.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sv *StockV1Query) GroupBy(field string, fields ...string) *StockV1GroupBy {
	grbuild := &StockV1GroupBy{config: sv.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sv.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sv.sqlQuery(ctx), nil
	}
	grbuild.label = stockv1.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.StockV1.Query().
//		Select(stockv1.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (sv *StockV1Query) Select(fields ...string) *StockV1Select {
	sv.fields = append(sv.fields, fields...)
	selbuild := &StockV1Select{StockV1Query: sv}
	selbuild.label = stockv1.Label
	selbuild.flds, selbuild.scan = &sv.fields, selbuild.Scan
	return selbuild
}

func (sv *StockV1Query) prepareQuery(ctx context.Context) error {
	for _, f := range sv.fields {
		if !stockv1.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sv.path != nil {
		prev, err := sv.path(ctx)
		if err != nil {
			return err
		}
		sv.sql = prev
	}
	if stockv1.Policy == nil {
		return errors.New("ent: uninitialized stockv1.Policy (forgotten import ent/runtime?)")
	}
	if err := stockv1.Policy.EvalQuery(ctx, sv); err != nil {
		return err
	}
	return nil
}

func (sv *StockV1Query) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StockV1, error) {
	var (
		nodes = []*StockV1{}
		_spec = sv.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*StockV1).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &StockV1{config: sv.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(sv.modifiers) > 0 {
		_spec.Modifiers = sv.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sv.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sv *StockV1Query) sqlCount(ctx context.Context) (int, error) {
	_spec := sv.querySpec()
	if len(sv.modifiers) > 0 {
		_spec.Modifiers = sv.modifiers
	}
	_spec.Node.Columns = sv.fields
	if len(sv.fields) > 0 {
		_spec.Unique = sv.unique != nil && *sv.unique
	}
	return sqlgraph.CountNodes(ctx, sv.driver, _spec)
}

func (sv *StockV1Query) sqlExist(ctx context.Context) (bool, error) {
	n, err := sv.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sv *StockV1Query) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   stockv1.Table,
			Columns: stockv1.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: stockv1.FieldID,
			},
		},
		From:   sv.sql,
		Unique: true,
	}
	if unique := sv.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sv.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockv1.FieldID)
		for i := range fields {
			if fields[i] != stockv1.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sv.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sv.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sv.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sv.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sv *StockV1Query) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sv.driver.Dialect())
	t1 := builder.Table(stockv1.Table)
	columns := sv.fields
	if len(columns) == 0 {
		columns = stockv1.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sv.sql != nil {
		selector = sv.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sv.unique != nil && *sv.unique {
		selector.Distinct()
	}
	for _, m := range sv.modifiers {
		m(selector)
	}
	for _, p := range sv.predicates {
		p(selector)
	}
	for _, p := range sv.order {
		p(selector)
	}
	if offset := sv.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sv.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (sv *StockV1Query) ForUpdate(opts ...sql.LockOption) *StockV1Query {
	if sv.driver.Dialect() == dialect.Postgres {
		sv.Unique(false)
	}
	sv.modifiers = append(sv.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return sv
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (sv *StockV1Query) ForShare(opts ...sql.LockOption) *StockV1Query {
	if sv.driver.Dialect() == dialect.Postgres {
		sv.Unique(false)
	}
	sv.modifiers = append(sv.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return sv
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sv *StockV1Query) Modify(modifiers ...func(s *sql.Selector)) *StockV1Select {
	sv.modifiers = append(sv.modifiers, modifiers...)
	return sv.Select()
}

// StockV1GroupBy is the group-by builder for StockV1 entities.
type StockV1GroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (svb *StockV1GroupBy) Aggregate(fns ...AggregateFunc) *StockV1GroupBy {
	svb.fns = append(svb.fns, fns...)
	return svb
}

// Scan applies the group-by query and scans the result into the given value.
func (svb *StockV1GroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := svb.path(ctx)
	if err != nil {
		return err
	}
	svb.sql = query
	return svb.sqlScan(ctx, v)
}

func (svb *StockV1GroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range svb.fields {
		if !stockv1.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := svb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (svb *StockV1GroupBy) sqlQuery() *sql.Selector {
	selector := svb.sql.Select()
	aggregation := make([]string, 0, len(svb.fns))
	for _, fn := range svb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(svb.fields)+len(svb.fns))
		for _, f := range svb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(svb.fields...)...)
}

// StockV1Select is the builder for selecting fields of StockV1 entities.
type StockV1Select struct {
	*StockV1Query
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sv *StockV1Select) Scan(ctx context.Context, v interface{}) error {
	if err := sv.prepareQuery(ctx); err != nil {
		return err
	}
	sv.sql = sv.StockV1Query.sqlQuery(ctx)
	return sv.sqlScan(ctx, v)
}

func (sv *StockV1Select) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sv.sql.Query()
	if err := sv.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sv *StockV1Select) Modify(modifiers ...func(s *sql.Selector)) *StockV1Select {
	sv.modifiers = append(sv.modifiers, modifiers...)
	return sv
}
