// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppGood is the predicate function for appgood builders.
type AppGood func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// DeviceInfo is the predicate function for deviceinfo builders.
type DeviceInfo func(*sql.Selector)

// ExtraInfo is the predicate function for extrainfo builders.
type ExtraInfo func(*sql.Selector)

// Good is the predicate function for good builders.
type Good func(*sql.Selector)

// Promotion is the predicate function for promotion builders.
type Promotion func(*sql.Selector)

// Recommend is the predicate function for recommend builders.
type Recommend func(*sql.Selector)

// StockV1 is the predicate function for stockv1 builders.
type StockV1 func(*sql.Selector)

// SubGood is the predicate function for subgood builders.
type SubGood func(*sql.Selector)

// VendorLocation is the predicate function for vendorlocation builders.
type VendorLocation func(*sql.Selector)
